repos:
    - repo: local
      hooks:
          - id: black
            name: black
            description: "Black: The uncompromising Python code formatter"
            entry: black
            language: python
            minimum_pre_commit_version: 2.9.2
            require_serial: true
            types_or: [python, pyi]

          - id: codespell
            name: codespell
            description: Checks for common misspellings in text files.
            entry: codespell
            language: python
            types: [text]
          
          - id: pytest
            name: pytest
            description: Test the unit test
            entry: pytest ./openbharatocr/unit_tests/
            language: python
            types: [python]
